const data_link = [
    "ke-dao-mo.html",
    "baseball.html",
    "gakuran.html",
    "barbercon.html",
    "racingboy.html",
    "ke-dao-mo.html",
    "baseball.html",
    "gakuran.html",
    "barbercon.html",
    "racingboy.html",
    "ke-dao-mo.html",
    "baseball.html",
    "gakuran.html",
    "barbercon.html",
    "racingboy.html",
];
